### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by manuchap** [bitaculous/cab#1]
Hi, I'm a big locomotive user and I'd just like to know what your app does.
(sry to sound noob, kinda lurking about github for everything locomotive related)

**Comment by mkempe** [comment]
Hey Manu,

thanks for the interest. Cab will eventually become the new UI for Locomotive. Eventually in big letter, due to lack of time and the Locomotive team still has to decide if Ember.js is the right framework, you can find the discussion here: https://gitter.im/locomotivecms/v3

Personally i think Ember.js is a great framework, now i have to prove it and convince the team :smile:

**Comment by manuchap** [comment]
Thnx for answering. +1 for ember :-)
I missed the live chat about v3 the other day. I’m also try to participate with my little wits, it’ll probably be frontend stuff (i added bootstrap and foundation so far) bug reporting (wagon app ,engine) and tutorials.
(that is if i don’t fully switch to meteor ;-)
